<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Rahul-PC" name="testcase.testOne.TestCustomeAnnotation" tests="4" failures="1" timestamp="27 Sep 2015 03:34:25 GMT" time="0.016" errors="0">
  <testcase name="TestCaseLogin_one" time="0.000" classname="testcase.testOne.TestCustomeAnnotation">
    <failure type="java.lang.RuntimeException" message="java.io.FileNotFoundException: Xlsx File Not Found : Did you forget to use @XlsxFilePath with @Test method">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: Xlsx File Not Found : Did you forget to use @XlsxFilePath with @Test method
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:161)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:429)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.io.FileNotFoundException: Xlsx File Not Found : Did you forget to use @XlsxFilePath with @Test method
	at helper.DataProviderClass.getData(DataProviderClass.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:135)
	... 20 more
]]>
    </failure>
  </testcase> <!-- TestCaseLogin_one -->
  <testcase name="TestCaseLogin" time="0.016" classname="testcase.testOne.TestCustomeAnnotation"/>
  <testcase name="TestCaseLogin" time="0.000" classname="testcase.testOne.TestCustomeAnnotation"/>
  <testcase name="TestCaseLogin" time="0.000" classname="testcase.testOne.TestCustomeAnnotation"/>
</testsuite> <!-- testcase.testOne.TestCustomeAnnotation -->
